Travis debug
Signed-off-by: gkGaneshR <gkganesh126@gmail.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -44,18 +44,18 @@ install:
     - make
 
     - if [ $? -eq "0" ]; then
-        echo "No error"
+        echo "No error";
     - else
-        echo "Error"
+        echo "Error";
       fi
 
 
 #Check for build success or failure
     - if [ -e cmd/zrepl/.libs/zrepl -a -e cmd/zpool/.libs/zpool -a -e cmd/zfs/.libs/zfs ]; then
-       echo "Build finished; Binaries are available"
+       echo "Build finished; Binaries are available";
       else
-       echo "Build failure; Binaries are unavailable"
-       #exit 1
+       echo "Build failure; Binaries are unavailable";
+       #exit 1;
       fi
 
     - sudo docker build -f Dockerfile.Baseimage -t openebs/cstor-base:ci --build-arg BUILD_DATE=${BUILD_DATE} . 
